name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  Unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Go Private Modules
        run: |
          GOPRIVATE=${GOPRIVATE:=github.com/NSXBet/*}
          echo "GOPRIVATE=$GOPRIVATE" >> $GITHUB_ENV
          git config --global url."https://${{ secrets.GHA_PAT }}@github.com/".insteadOf "https://github.com/"
      - name: Set environment
        run: echo "ENVIRONMENT=test" >> $GITHUB_ENV
      - name: Test
        run: make gotestsum run-unit && make coverage-package coverage > ./coverage-results && echo "<pre><code>$(cat ./coverage-results)</code></pre>" >> $GITHUB_STEP_SUMMARY
  Format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Go Private Modules
        run: |
          GOPRIVATE=${GOPRIVATE:=github.com/NSXBet/*}
          echo "GOPRIVATE=$GOPRIVATE" >> $GITHUB_ENV
          git config --global url."https://${{ secrets.GHA_PAT }}@github.com/".insteadOf "https://github.com/"
      - name: Format
        run: |
          make format && (git diff --quiet --exit-code || (echo "‚ùå Uncommitted changes detected. Please run <code>make format</code> and commit them." >> $GITHUB_STEP_SUMMARY && echo "<pre lang=\"diff\"><code>$(git diff)</code></pre>" >> $GITHUB_STEP_SUMMARY && exit 1))
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Go Private Modules
        run: |
          GOPRIVATE=${GOPRIVATE:=github.com/NSXBet/*}
          echo "GOPRIVATE=$GOPRIVATE" >> $GITHUB_ENV
          git config --global url."https://${{ secrets.GHA_PAT }}@github.com/".insteadOf "https://github.com/"
      - name: Lint
        run: |
          git fetch origin main:main && make lint
